import { readFileSync, writeFileSync, readdirSync, existsSync, statSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join, extname } from 'node:path';

function readText(p) {
  return readFileSync(p, 'utf-8').replace(/\r\n/g, '\n');
}


const REPO_ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const BUILTIN_DIR = join(REPO_ROOT, 'packages', 'core', 'src', 'skills', 'builtin');
const OUT_TS = join(
  REPO_ROOT,
  'packages',
  'core',
  'src',
  'skills',
  'bakedSkills.generated.ts',
);

/** 与 SkillLoader.loadSupportFiles 的 textExtensions 保持一致 */
const TEXT_EXTENSIONS = new Set([
  '.md', '.txt', '.json', '.yaml', '.yml', '.sh', '.js', '.ts', '.py', '.mjs', '.cjs',
]);

/** 这些扩展名不能烘焙成字符串 —— 它们要被 node/shell 当真文件执行, 必须随包落到磁盘。
 *  目前 builtin/ 下没有, 出现即 fail-loud 提醒人显式处理 (参照 pptx-scripts)。 */
const EXECUTABLE_EXTENSIONS = new Set(['.mjs', '.cjs', '.js', '.sh', '.py']);

if (!existsSync(BUILTIN_DIR)) {
  throw new Error(`[bake-skills] builtin 目录不存在: ${BUILTIN_DIR} — 必须在 repo 根跑`);
}

/** { "pptx-deck-writer": { "SKILL.md": "...", "references/visual-rules.md": "..." } } */
const snapshot = {};
let fileCount = 0;

for (const skillId of readdirSync(BUILTIN_DIR).sort()) {
  const skillDir = join(BUILTIN_DIR, skillId);
  if (!statSync(skillDir).isDirectory()) continue;

  const skillMd = join(skillDir, 'SKILL.md');
  if (!existsSync(skillMd)) {
    throw new Error(`[bake-skills] ${skillId}/ 里没有 SKILL.md — 不是合法技能目录, fail-loud`);
  }

  const files = { 'SKILL.md': readText(skillMd) };
  fileCount++;

  /* 只递一层子目录 — 跟 loadSupportFiles 的 walk 规则一致 */
  for (const entry of readdirSync(skillDir, { withFileTypes: true }).sort((a, b) =>
    a.name.localeCompare(b.name),
  )) {
    if (entry.name.startsWith('.') || entry.name === 'node_modules') continue;
    if (!entry.isDirectory()) continue;
    const subDir = join(skillDir, entry.name);
    for (const f of readdirSync(subDir, { withFileTypes: true }).sort((a, b) =>
      a.name.localeCompare(b.name),
    )) {
      if (!f.isFile()) continue;
      const ext = extname(f.name).toLowerCase();
      if (EXECUTABLE_EXTENSIONS.has(ext)) {
        throw new Error(
          `[bake-skills] ${skillId}/${entry.name}/${f.name} 是可执行文件 (${ext}) —— ` +
            `不能烘焙成字符串, 需要随包发布到确定路径 (参照 pptx-scripts 的做法) 并在此显式排除。`,
        );
      }
      if (!TEXT_EXTENSIONS.has(ext)) continue;
      files[`${entry.name}/${f.name}`] = readText(join(subDir, f.name));
      fileCount++;
    }
  }

  snapshot[skillId] = files;
}

const skillIds = Object.keys(snapshot);
if (skillIds.length === 0) {
  throw new Error('[bake-skills] 一个内置技能都没扫到 — 大概率路径错了, fail-loud');
}

const json = JSON.stringify(snapshot);
const b64 = Buffer.from(json, 'utf-8').toString('base64');

/* 自检: 解码必须逐字节还原 (跟 bake-prompts / bake-schemas 同款守卫) */
if (Buffer.from(b64, 'base64').toString('utf-8') !== json) {
  throw new Error('[bake-skills] roundtrip mismatch — 烘焙结果与源不一致');
}

const banner =
  `/**\n` +
  ` * AUTO-GENERATED by scripts/bake-skills.mjs — 请勿手改。\n` +
  ` * 源: neox-core 的 skills/builtin 目录 (${skillIds.length} 个技能 / ${fileCount} 个文件)\n` +
  ` * 内置技能: ${skillIds.join(', ')}\n` +
  ` * 改 SKILL.md 请改源文件再跑: node scripts/bake-skills.mjs\n` +
  ` */`;

const body =
  `${banner}\n` +
  `const _b64 = '${b64}';\n` +
  `\n` +
  `/** 技能 id → (技能目录内相对路径 → 文件原文). 磁盘 builtin/ 不可用时读这份。 */\n` +
  `export type BakedSkillSnapshot = Record<string, Record<string, string>>;\n` +
  `\n` +
  `let _cache: BakedSkillSnapshot | null = null;\n` +
  `export function getBakedSkills(): BakedSkillSnapshot {\n` +
  `  if (!_cache) _cache = JSON.parse(Buffer.from(_b64, 'base64').toString('utf-8'));\n` +
  `  return _cache!;\n` +
  `}\n`;

writeFileSync(OUT_TS, body, 'utf-8');
console.log(
  `[bake-skills] builtin/ (${skillIds.length} skills, ${fileCount} files, ${json.length}B) → ` +
    `packages/core/src/skills/bakedSkills.generated.ts (base64 ${b64.length}B)`,
);
