/**
 * bake-schemas.mjs — 把 schemas/ 下所有 yaml 烘焙成一个 base64 常量 .ts, 让发行版
 *                    (Electron asar / bun --compile 单文件) 运行时不依赖磁盘上的 schemas/ 目录。
 *
 * 背景 (2026-07-18): schemas/ 既不在 electron-builder 的 files/extraResources 里,
 * 也没被 bun --compile 内嵌 → 发行版 loader.defaultSchemasDir() 找不到目录:
 *   · CLI 二进制: 全局 neox 换模型静默丢 thinking/effort (2026-07-17 事故根因)
 *   · 桌面打包版: cwd 是 '/' , import.meta.url 在 asar 内, 四个 candidate 全落空
 *
 * 方案跟 bake-prompts.mjs 同款 (仓库既有惯例, 不引新机制):
 *   单一真相源 = schemas/*.yaml (人类可编辑), .generated.ts 由本脚本生成并提交。
 *   烘焙产物进 kernel bundle → 桌面 (tsup→asar) 和 CLI (bun --compile) 同时拿到, 一个机制盖两端。
 *
 * 优先级 (见 loader.ts): NEOX_SCHEMAS_DIR > 磁盘 schemas/ (dev 改 yaml 即时生效) > 烘焙快照。
 * 三者全空才抛错 —— 永远不静默降级。
 *
 * 改 yaml 后跑一次: node scripts/bake-schemas.mjs (build:packages 已自动调用)。
 */
import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

/* 行尾统一成 LF —— 这些文本会**原样进提示词**。
 *
 *   2026-08-18: bakedSkills / gptAgentsInstructions 两个快照里混进了 CRLF (在 Windows 上
 *   重新烘焙的那次带进来的), 后果两条:
 *     · 同一份源码, Windows 构建和 mac 构建打出**字节不同**的提示词 → prompt 缓存全废
 *       (system 段必须字节稳定, 见 feedback_system_prompt_must_be_byte_stable_for_cache)
 *     · 两台机器互相把对方的快照改回去, git 里永久 churn
 *   在读取处归一, 产物就跟 checkout 的行尾设置无关了。 */
function readText(p) {
  return readFileSync(p, 'utf-8').replace(/\r\n/g, '\n');
}


const REPO_ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SCHEMAS_DIR = join(REPO_ROOT, 'schemas');
const OUT_TS = join(REPO_ROOT, 'packages', 'kernel', 'src', 'schemas', 'bakedSchemas.generated.ts');

/** loader.readYamlDir 只读这四个子目录 — 烘焙范围跟它严格一致 */
const SUBDIRS = ['protocols', 'providers', 'models', 'families'];

if (!existsSync(SCHEMAS_DIR)) {
  throw new Error(`[bake-schemas] schemas/ 不存在: ${SCHEMAS_DIR} — 必须在 repo 根跑`);
}

/** { "models": { "claude-opus-4-8.yaml": "<raw yaml>" }, ... } */
const snapshot = {};
let fileCount = 0;

for (const sub of SUBDIRS) {
  const dir = join(SCHEMAS_DIR, sub);
  if (!existsSync(dir)) {
    throw new Error(`[bake-schemas] 缺子目录 schemas/${sub} — loader 预期它存在`);
  }
  const files = {};
  for (const fname of readdirSync(dir).sort()) {
    if (!fname.endsWith('.yaml') && !fname.endsWith('.yml')) continue;
    files[fname] = readText(join(dir, fname));
    fileCount++;
  }
  if (Object.keys(files).length === 0) {
    throw new Error(`[bake-schemas] schemas/${sub} 一个 yaml 都没有 — 大概率路径错了, fail-loud`);
  }
  snapshot[sub] = files;
}

const json = JSON.stringify(snapshot);
const b64 = Buffer.from(json, 'utf-8').toString('base64');

/* 自检: 解码必须逐字节还原, 否则 fail-loud (跟 bake-prompts 同款守卫) */
const roundtrip = Buffer.from(b64, 'base64').toString('utf-8');
if (roundtrip !== json) {
  throw new Error('[bake-schemas] roundtrip mismatch — 烘焙结果与源不一致');
}

const banner =
  `/**\n` +
  ` * AUTO-GENERATED by scripts/bake-schemas.mjs — 请勿手改。\n` +
  ` * 源: schemas/{${SUBDIRS.join(',')}}/*.yaml (${fileCount} 个文件)\n` +
  ` * 改 schema 请改 yaml 再跑: node scripts/bake-schemas.mjs\n` +
  ` */`;

const body =
  `${banner}\n` +
  `const _b64 = '${b64}';\n` +
  `\n` +
  `/** 子目录名 → (文件名 → yaml 原文). loader 在磁盘 schemas/ 不可用时读这份。 */\n` +
  `export type BakedSchemaSnapshot = Record<string, Record<string, string>>;\n` +
  `\n` +
  `let _cache: BakedSchemaSnapshot | null = null;\n` +
  `export function getBakedSchemas(): BakedSchemaSnapshot {\n` +
  `  if (!_cache) _cache = JSON.parse(Buffer.from(_b64, 'base64').toString('utf-8'));\n` +
  `  return _cache!;\n` +
  `}\n`;

writeFileSync(OUT_TS, body, 'utf-8');
console.log(
  `[bake-schemas] schemas/ (${fileCount} yaml, ${json.length}B) → ` +
    `packages/kernel/src/schemas/bakedSchemas.generated.ts (base64 ${b64.length}B)`,
);
