/**
 * bake-prompts.mjs — 把核心系统提示词 .md 烘焙成 base64 常量 .ts,避免明文随包分发。
 *
 * 背景 (2026-07-17): gpt-agents-instructions.md 原本被 tsup / kernel build 原样 copy 进
 * asar,`asar extract` 解包即可 `cat` 到完整 agent 指令 —— 唯一零成本被白扒的核心 IP。
 * 烘焙成 base64 常量后:
 *   · 不再有独立 .md 文件躺在产物里 (解包无法直接 cat)
 *   · 内容进 JS bundle → 桌面走 fortress javascript-obfuscator 字符串数组加密 + polymorphic XOR
 *   · CLI 端至少不是明文可 grep 的独立文件 (base64,在 3MB minified blob 里)
 *
 * 单一真相源 = .md (人类可编辑),.generated.ts 由本脚本生成并提交。
 * 编辑提示词后跑一次: node scripts/bake-prompts.mjs (build:packages 已自动调用)。
 *
 * base64 不是加密,是"去明文化" —— 对提示词这类非密钥资产,配合桌面混淆已足够抬高扒取成本。
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

/* 行尾统一成 LF —— 这些文本会**原样进提示词**。
 *
 *   2026-08-18: bakedSkills / gptAgentsInstructions 两个快照里混进了 CRLF (在 Windows 上
 *   重新烘焙的那次带进来的), 后果两条:
 *     · 同一份源码, Windows 构建和 mac 构建打出**字节不同**的提示词 → prompt 缓存全废
 *       (system 段必须字节稳定, 见 feedback_system_prompt_must_be_byte_stable_for_cache)
 *     · 两台机器互相把对方的快照改回去, git 里永久 churn
 *   在读取处归一, 产物就跟 checkout 的行尾设置无关了。 */
function readText(p) {
  return readFileSync(p, 'utf-8').replace(/\r\n/g, '\n');
}


const REPO_ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');

/** 要烘焙的提示词: { md 源, 生成的 .ts, 导出名 } */
const TARGETS = [
  {
    md: 'packages/kernel/src/prompts/gpt-agents-instructions.md',
    ts: 'packages/kernel/src/prompts/gptAgentsInstructions.generated.ts',
    exportName: 'GPT_AGENTS_INSTRUCTIONS',
  },
];

function bake({ md, ts, exportName }) {
  const srcPath = join(REPO_ROOT, md);
  const outPath = join(REPO_ROOT, ts);
  const raw = readText(srcPath);
  const b64 = Buffer.from(raw, 'utf-8').toString('base64');

  const banner = `/**\n * AUTO-GENERATED by scripts/bake-prompts.mjs — 请勿手改。\n * 源: ${md}\n * 编辑提示词请改 .md 再跑: node scripts/bake-prompts.mjs\n */`;
  const body =
    `${banner}\n` +
    `const _b64 = '${b64}';\n` +
    `export const ${exportName} = Buffer.from(_b64, 'base64').toString('utf-8');\n`;

  writeFileSync(outPath, body, 'utf-8');
  console.log(`[bake-prompts] ${md} (${raw.length}B) → ${ts} (base64 ${b64.length}B)`);

  // 自检: 解码必须逐字节还原,否则 fail-loud
  const roundtrip = Buffer.from(b64, 'base64').toString('utf-8');
  if (roundtrip !== raw) {
    throw new Error(`[bake-prompts] roundtrip mismatch for ${md} — 烘焙结果与源不一致`);
  }
}

for (const t of TARGETS) bake(t);
console.log('[bake-prompts] done.');
