#!/usr/bin/env node
/**
 * schema:sync — generate idempotent SQL from schemas/ to populate neoxcloud DB.
 *
 *   Output is plain SQL on stdout. Wrapped in BEGIN/COMMIT so it's atomic.
 *   Uses INSERT ... ON CONFLICT DO UPDATE so re-running is safe; per-channel
 *   override fields (weight, priority, api_key_enc, max_rpm, etc.) are NOT
 *   touched — only the schema-owned fields are sync'd.
 *
 *   Usage:
 *     node scripts/schema-sync.mjs > /tmp/sync.sql
 *     # review the file then:
 *     scp /tmp/sync.sql root@prod:/tmp/
 *     ssh root@prod 'docker exec -i neox-postgres psql -U neox -d neoxcloud < /tmp/sync.sql'
 *
 *   Schema-owned fields (will be set/updated):
 *     gateway_providers: base_url, api_protocol (from protocol.api_path → /v1/chat/...),
 *                        type ('openai' if openai-chat else slug)
 *     models:            display_name, family, context_window, max_output_tokens,
 *                        input_price_micros_per_mtok, cached_input_price_micros_per_mtok,
 *                        output_price_micros_per_mtok, currency, availability, metadata
 *     model_channels:    upstream_model_name, api_endpoint
 *                        (NOT weight, priority, enabled, api_key_enc, max_rpm, max_tpm)
 *
 *   Override fields (untouched on re-sync):
 *     gateway_providers.api_key_enc, enabled, status, priority, retry_policy,
 *                       rate_limit_rpm, extra_headers, notes
 *     models.enabled
 *     model_channels.weight, priority, enabled, max_rpm, max_tpm
 */

import { fileURLToPath } from 'node:url';
import { loadSchemas } from '../packages/kernel/dist/schemas/loader.js';

function sqlString(v) {
  if (v === null || v === undefined) return 'NULL';
  return `'${String(v).replace(/'/g, "''")}'`;
}
function sqlJson(obj) {
  return `'${JSON.stringify(obj).replace(/'/g, "''")}'::jsonb`;
}
function sqlNum(n) {
  if (n === null || n === undefined) return 'NULL';
  return String(n);
}

/* 路径只算一次, 用 fileURLToPath —— Windows 上 .pathname 是 `/E:/...`, 加载器空手而归
 * (而脚本"成功"输出一段没有 schema 的 SQL, 比报错更难发现)。 */
const SCHEMAS_DIR = fileURLToPath(new URL('../schemas/', import.meta.url));
const registry = loadSchemas({ dir: SCHEMAS_DIR });

const out = [];
out.push('-- Generated by scripts/schema-sync.mjs');
out.push(`-- Source: schemas/ at ${SCHEMAS_DIR}`);
out.push('-- Wrap in transaction so failure rolls back cleanly');
out.push('BEGIN;');
out.push('');

// ── 1. gateway_providers ────────────────────────────────────────
out.push('-- 1. gateway_providers — base_url / api_protocol from yaml');
out.push('-- (api_key_enc / enabled / status / priority / retry / rate_limit / extra_headers / notes are user-managed; NOT touched)');
for (const p of registry.providers.values()) {
  const protocol = registry.protocols.get(p.protocol);
  // type 字段: openai-chat → 'openai', anthropic-messages → 'anthropic' (DB enum 假设)
  const type = p.protocol === 'openai-chat' ? 'openai'
             : p.protocol === 'anthropic-messages' ? 'anthropic'
             : p.protocol;
  out.push(`-- ${p.slug} (${p.display_name})`);
  out.push(`INSERT INTO gateway_providers (id, slug, name, type, api_protocol, base_url, enabled, status, created_at, updated_at)`);
  out.push(`VALUES (${sqlString(p.id)}, ${sqlString(p.slug)}, ${sqlString(p.display_name)}, ${sqlString(type)}, ${sqlString(p.protocol)}, ${sqlString(p.base_url)}, false, 'draft',`);
  out.push(`  to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),`);
  out.push(`  to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'))`);
  out.push(`ON CONFLICT (id) DO UPDATE SET`);
  out.push(`  base_url = EXCLUDED.base_url,`);
  out.push(`  api_protocol = EXCLUDED.api_protocol,`);
  out.push(`  type = EXCLUDED.type,`);
  out.push(`  name = EXCLUDED.name,`);
  out.push(`  updated_at = to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"');`);
  out.push('');
}

// ── 2. models ───────────────────────────────────────────────────
out.push('-- 2. models — pricing / capabilities from yaml');
out.push('-- (enabled flag is user-managed; NOT touched)');
for (const m of registry.models.values()) {
  const inputMicros = Math.round((m.pricing.input_per_mtok || 0) * 1_000_000);
  const cachedMicros = Math.round((m.pricing.cached_input_per_mtok || 0) * 1_000_000);
  const outputMicros = Math.round((m.pricing.output_per_mtok || 0) * 1_000_000);
  const metadata = {
    family: m.family,
    capabilities: m.capabilities || {},
    effort_map: m.effort_map || {},
    vendor: m.vendor || null,
    released: m.released || null,
  };
  out.push(`-- ${m.display_name} (${m.id})`);
  out.push(`INSERT INTO models (id, display_name, family, context_window, max_output_tokens,`);
  out.push(`  input_price_micros_per_mtok, cached_input_price_micros_per_mtok, output_price_micros_per_mtok,`);
  out.push(`  platform_fee_micros_per_mtok, currency, enabled, availability, metadata, released_at, created_at, updated_at)`);
  out.push(`VALUES (${sqlString(m.id)}, ${sqlString(m.display_name)}, ${sqlString(m.family)},`);
  out.push(`  ${sqlNum(m.context_window)}, ${sqlNum(m.max_output_tokens)},`);
  out.push(`  ${sqlNum(inputMicros)}, ${sqlNum(cachedMicros)}, ${sqlNum(outputMicros)},`);
  out.push(`  0, ${sqlString(m.pricing.currency || 'USD')}, true, ${sqlString(m.availability)},`);
  out.push(`  ${sqlJson(metadata)}, ${sqlString(m.released || null)},`);
  out.push(`  to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),`);
  out.push(`  to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'))`);
  out.push(`ON CONFLICT (id) DO UPDATE SET`);
  out.push(`  display_name = EXCLUDED.display_name,`);
  out.push(`  family = EXCLUDED.family,`);
  out.push(`  context_window = EXCLUDED.context_window,`);
  out.push(`  max_output_tokens = EXCLUDED.max_output_tokens,`);
  out.push(`  input_price_micros_per_mtok = EXCLUDED.input_price_micros_per_mtok,`);
  out.push(`  cached_input_price_micros_per_mtok = EXCLUDED.cached_input_price_micros_per_mtok,`);
  out.push(`  output_price_micros_per_mtok = EXCLUDED.output_price_micros_per_mtok,`);
  out.push(`  availability = EXCLUDED.availability,`);
  out.push(`  metadata = EXCLUDED.metadata,`);
  out.push(`  updated_at = to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"');`);
  out.push('');
}

// ── 3. model_channels ──────────────────────────────────────────
out.push('-- 3. model_channels — upstream_model_name from yaml.upstream_slugs');
out.push('-- (weight / priority / enabled / api_key_enc / max_rpm / max_tpm are channel admin-managed; NOT touched)');
for (const m of registry.models.values()) {
  for (const [providerId, slug] of Object.entries(m.upstream_slugs)) {
    const provider = registry.providers.get(providerId);
    if (!provider) continue;
    const channelId = `ch_${m.id.replace(/[^a-z0-9]/gi, '').slice(0, 14)}_${provider.slug}`;
    const protocol = registry.protocols.get(provider.protocol);
    const apiEndpoint = protocol?.api_path || '/v1/chat/completions';
    const inputMicros = Math.round((m.pricing.input_per_mtok || 0) * 1_000_000);
    const cachedMicros = Math.round((m.pricing.cached_input_per_mtok || 0) * 1_000_000);
    const outputMicros = Math.round((m.pricing.output_per_mtok || 0) * 1_000_000);
    out.push(`-- ${m.id} via ${provider.slug}`);
    out.push(`INSERT INTO model_channels (id, model_id, provider_id, upstream_model_name,`);
    out.push(`  weight, priority, enabled, input_cost_micros_per_mtok, cached_input_cost_micros_per_mtok,`);
    out.push(`  output_cost_micros_per_mtok, metadata, api_endpoint, created_at, updated_at)`);
    out.push(`VALUES (${sqlString(channelId)}, ${sqlString(m.id)}, ${sqlString(providerId)}, ${sqlString(slug)},`);
    out.push(`  100, 100, true, ${sqlNum(inputMicros)}, ${sqlNum(cachedMicros)}, ${sqlNum(outputMicros)},`);
    out.push(`  '{}'::jsonb, ${sqlString(apiEndpoint)},`);
    out.push(`  to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),`);
    out.push(`  to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'))`);
    out.push(`ON CONFLICT (model_id, provider_id) DO UPDATE SET`);
    out.push(`  upstream_model_name = EXCLUDED.upstream_model_name,`);
    out.push(`  api_endpoint = EXCLUDED.api_endpoint,`);
    out.push(`  input_cost_micros_per_mtok = EXCLUDED.input_cost_micros_per_mtok,`);
    out.push(`  cached_input_cost_micros_per_mtok = EXCLUDED.cached_input_cost_micros_per_mtok,`);
    out.push(`  output_cost_micros_per_mtok = EXCLUDED.output_cost_micros_per_mtok,`);
    out.push(`  updated_at = to_char((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"');`);
    out.push('');
  }
}

out.push('COMMIT;');
out.push('');
out.push(`-- Summary: ${registry.providers.size} providers · ${registry.models.size} models · ${
  Array.from(registry.models.values()).reduce((s, m) => s + Object.keys(m.upstream_slugs).length, 0)
} channels`);

process.stdout.write(out.join('\n') + '\n');
